### ISSUE TITLE
Export fails when file extensions are removed

### ISSUE THREAD

**Issue by ArthurClemens** [atomicojs/exports#1]
I was trying to convert the example code from `base` to TypeScript (renaming `brand.jsx` to `brand.tsx` and so on), and clean up seemingly unnecessary file extensions. For example:

```ts
import { Hello } from "./hello/hello.jsx"
```
to
```ts
import { Hello } from "./hello/hello"
```
With the other change renaming `components.js` to `components.ts` (also in package.json).

The code with these changes does run, but the export script fails:

```bash
Exports
[01:06:03] Initializing...
[01:06:03] Generating outputs with esbuild...
[01:06:03] Esbuild completed...
[01:06:03] Preparing package.json...
[01:06:03] Preparing types...
(node:38990) UnhandledPromiseRejectionWarning: Error: Command failed: npx tsc src/components.ts  --moduleResolution Node --target ESNext --listEmittedFiles true --strict true --jsx react-jsx --jsxImportSource atomico --allowJs true --declaration true --emitDeclarationOnly true --outDir ./types --lib ESNext,DOM,DOM.Iterable

    at ChildProcess.exithandler (child_process.js:319:12)
    at ChildProcess.emit (events.js:376:20)
    at maybeClose (internal/child_process.js:1055:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:376:20)
    at Pipe.<anonymous> (net.js:673:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:38990) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:38990) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by UpperCod** [comment]
Hi @ArthurClemens , thanks for commenting on the bug, apparently the error is due to the import of the css asset.

I have fixed this in version `@atomico/exports@0.18.4`, it adds default types to support asset import
